[2023-03-14T04:27:10.397+0000] {processor.py:153} INFO - Started process (PID=6828) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:10.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:27:10.399+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:27:10.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:10.421+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:27:10.417+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:27:10.423+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:10.439+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T04:27:41.275+0000] {processor.py:153} INFO - Started process (PID=6940) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:41.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:27:41.277+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:27:41.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:41.293+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:27:41.291+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:27:41.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:27:41.313+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2023-03-14T04:28:11.864+0000] {processor.py:153} INFO - Started process (PID=7028) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:11.865+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:28:11.866+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:28:11.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:11.879+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:28:11.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:28:11.880+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:11.905+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T04:28:42.223+0000] {processor.py:153} INFO - Started process (PID=7140) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:42.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:28:42.224+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:28:42.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:42.240+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:28:42.237+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:28:42.241+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:28:42.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-14T04:29:13.050+0000] {processor.py:153} INFO - Started process (PID=7228) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:13.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:29:13.052+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:29:13.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:13.064+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:29:13.062+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:29:13.064+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:13.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T04:29:43.835+0000] {processor.py:153} INFO - Started process (PID=7316) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:43.836+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:29:43.838+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:29:43.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:43.863+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:29:43.859+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:29:43.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:29:43.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.062 seconds
[2023-03-14T04:30:13.950+0000] {processor.py:153} INFO - Started process (PID=7428) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:13.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:30:13.952+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:30:13.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:13.968+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:30:13.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:30:13.969+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:13.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-14T04:30:44.434+0000] {processor.py:153} INFO - Started process (PID=7516) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:44.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:30:44.436+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:30:44.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:44.448+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:30:44.446+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:30:44.450+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:30:44.474+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T04:31:15.175+0000] {processor.py:153} INFO - Started process (PID=7604) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:15.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:31:15.176+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:31:15.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:15.194+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:31:15.191+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:31:15.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:15.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T04:31:45.544+0000] {processor.py:153} INFO - Started process (PID=7716) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:45.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:31:45.545+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:31:45.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:45.563+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:31:45.560+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:31:45.564+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:31:45.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.054 seconds
[2023-03-14T04:32:16.177+0000] {processor.py:153} INFO - Started process (PID=7804) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:16.178+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:32:16.178+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:32:16.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:16.192+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:32:16.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:32:16.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:16.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.034 seconds
[2023-03-14T04:32:46.483+0000] {processor.py:153} INFO - Started process (PID=7901) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:46.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:32:46.485+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:32:46.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:46.504+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:32:46.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:32:46.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:32:46.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T04:33:17.239+0000] {processor.py:153} INFO - Started process (PID=8004) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:17.240+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:33:17.241+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:33:17.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:17.260+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:33:17.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:33:17.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:17.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T04:33:47.639+0000] {processor.py:153} INFO - Started process (PID=8093) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:47.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:33:47.641+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:33:47.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:47.654+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:33:47.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:33:47.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:33:47.672+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.035 seconds
[2023-03-14T04:34:17.954+0000] {processor.py:153} INFO - Started process (PID=8205) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:17.956+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:34:17.957+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:34:17.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:17.977+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:34:17.974+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:34:17.978+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:18.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.060 seconds
[2023-03-14T04:34:48.812+0000] {processor.py:153} INFO - Started process (PID=8293) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:48.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:34:48.815+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:34:48.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:48.842+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:34:48.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:34:48.844+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:34:48.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.084 seconds
[2023-03-14T04:35:19.316+0000] {processor.py:153} INFO - Started process (PID=8390) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:19.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:35:19.318+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:35:19.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:19.336+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:35:19.333+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:35:19.337+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:19.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2023-03-14T04:35:49.876+0000] {processor.py:153} INFO - Started process (PID=8493) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:49.876+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:35:49.877+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:35:49.877+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:49.890+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:35:49.888+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:35:49.890+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:35:49.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.032 seconds
[2023-03-14T04:36:20.708+0000] {processor.py:153} INFO - Started process (PID=8581) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:20.710+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:36:20.710+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:36:20.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:20.728+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:36:20.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:36:20.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:20.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.039 seconds
[2023-03-14T04:36:51.010+0000] {processor.py:153} INFO - Started process (PID=8693) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:51.011+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:36:51.012+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:36:51.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:51.024+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:36:51.022+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:36:51.025+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:36:51.039+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.030 seconds
[2023-03-14T04:37:21.881+0000] {processor.py:153} INFO - Started process (PID=8781) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:21.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:37:21.883+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:37:21.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:21.898+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:37:21.896+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:37:21.899+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:21.926+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.047 seconds
[2023-03-14T04:37:52.580+0000] {processor.py:153} INFO - Started process (PID=8893) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:52.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:37:52.582+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:37:52.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:52.612+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:37:52.607+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:37:52.614+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:37:52.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.065 seconds
[2023-03-14T04:38:23.128+0000] {processor.py:153} INFO - Started process (PID=8981) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:23.129+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:38:23.129+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:38:23.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:23.142+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:38:23.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:38:23.143+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:23.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.031 seconds
[2023-03-14T04:38:53.812+0000] {processor.py:153} INFO - Started process (PID=9093) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:53.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:38:53.814+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:38:53.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:53.833+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:38:53.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:38:53.835+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:38:53.854+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T04:39:24.791+0000] {processor.py:153} INFO - Started process (PID=9181) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:24.793+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:39:24.794+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:39:24.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:24.809+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:39:24.806+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:39:24.811+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:24.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:39:55.130+0000] {processor.py:153} INFO - Started process (PID=9269) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:55.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:39:55.133+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:39:55.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:55.154+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:39:55.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:39:55.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:39:55.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.053 seconds
[2023-03-14T04:40:26.050+0000] {processor.py:153} INFO - Started process (PID=9381) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:26.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:40:26.051+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:40:26.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:26.064+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:40:26.062+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:40:26.065+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:26.090+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:40:56.710+0000] {processor.py:153} INFO - Started process (PID=9469) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:56.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:40:56.711+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:40:56.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:56.728+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:40:56.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:40:56.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:40:56.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T04:41:27.522+0000] {processor.py:153} INFO - Started process (PID=9566) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:27.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:41:27.524+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:41:27.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:27.544+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:41:27.541+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:41:27.546+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:27.566+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-14T04:41:57.645+0000] {processor.py:153} INFO - Started process (PID=9669) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:57.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:41:57.646+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:41:57.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:57.664+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:41:57.660+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:41:57.665+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:41:57.696+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.054 seconds
[2023-03-14T04:42:27.871+0000] {processor.py:153} INFO - Started process (PID=9757) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:27.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:42:27.874+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:42:27.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:27.900+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:42:27.896+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:42:27.901+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:27.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.055 seconds
[2023-03-14T04:42:58.478+0000] {processor.py:153} INFO - Started process (PID=9869) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:58.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:42:58.480+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:42:58.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:58.496+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:42:58.493+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:42:58.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:42:58.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2023-03-14T04:43:28.787+0000] {processor.py:153} INFO - Started process (PID=9958) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:28.788+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:43:28.789+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:43:28.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:28.811+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:43:28.807+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:43:28.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:28.843+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.059 seconds
[2023-03-14T04:43:59.111+0000] {processor.py:153} INFO - Started process (PID=10055) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:59.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:43:59.112+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:43:59.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:59.131+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:43:59.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:43:59.132+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:43:59.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:44:29.822+0000] {processor.py:153} INFO - Started process (PID=10158) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:44:29.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:44:29.823+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:44:29.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:44:29.840+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:44:29.837+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:44:29.841+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:44:29.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:45:00.215+0000] {processor.py:153} INFO - Started process (PID=10246) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:00.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:45:00.216+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:45:00.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:00.233+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:45:00.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:45:00.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:00.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.038 seconds
[2023-03-14T04:45:31.115+0000] {processor.py:153} INFO - Started process (PID=10358) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:31.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:45:31.117+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:45:31.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:31.133+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:45:31.131+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:45:31.135+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:45:31.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2023-03-14T04:46:01.525+0000] {processor.py:153} INFO - Started process (PID=10455) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:01.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:46:01.526+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:46:01.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:01.539+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:46:01.537+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:46:01.540+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:01.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:46:31.864+0000] {processor.py:153} INFO - Started process (PID=10558) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:31.865+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:46:31.865+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:46:31.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:31.881+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:46:31.878+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:46:31.882+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:46:31.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.039 seconds
[2023-03-14T04:47:02.568+0000] {processor.py:153} INFO - Started process (PID=10646) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:02.569+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:47:02.569+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:47:02.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:02.584+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:47:02.581+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:47:02.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:02.598+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.033 seconds
[2023-03-14T04:47:32.714+0000] {processor.py:153} INFO - Started process (PID=10758) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:32.715+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:47:32.715+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:47:32.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:32.732+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:47:32.729+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:47:32.733+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:47:32.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:48:03.063+0000] {processor.py:153} INFO - Started process (PID=10846) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:03.064+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:48:03.065+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:48:03.064+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:03.083+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:48:03.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:48:03.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:03.105+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2023-03-14T04:48:33.151+0000] {processor.py:153} INFO - Started process (PID=10958) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:33.152+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:48:33.153+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:48:33.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:33.170+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:48:33.168+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:48:33.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:48:33.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.039 seconds
[2023-03-14T04:49:03.333+0000] {processor.py:153} INFO - Started process (PID=11046) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:03.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:49:03.335+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:49:03.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:03.350+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:49:03.346+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:49:03.351+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:03.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-14T04:49:33.464+0000] {processor.py:153} INFO - Started process (PID=11134) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:33.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:49:33.465+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:49:33.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:33.479+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:49:33.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:49:33.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:49:33.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T04:50:04.362+0000] {processor.py:153} INFO - Started process (PID=11246) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:04.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:50:04.364+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:50:04.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:04.391+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:50:04.387+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:50:04.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:04.419+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.061 seconds
[2023-03-14T04:50:34.848+0000] {processor.py:153} INFO - Started process (PID=11335) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:34.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:50:34.850+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:50:34.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:34.874+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:50:34.870+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:50:34.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:50:34.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.059 seconds
[2023-03-14T04:51:05.726+0000] {processor.py:153} INFO - Started process (PID=11432) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:05.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:51:05.729+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:51:05.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:05.754+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:51:05.749+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:51:05.755+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:05.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.060 seconds
[2023-03-14T04:51:36.690+0000] {processor.py:153} INFO - Started process (PID=11535) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:36.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:51:36.692+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:51:36.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:36.713+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:51:36.710+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:51:36.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:51:36.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2023-03-14T04:52:07.392+0000] {processor.py:153} INFO - Started process (PID=11623) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:07.394+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:52:07.395+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:52:07.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:07.426+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:52:07.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:52:07.428+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:07.462+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.074 seconds
[2023-03-14T04:52:37.931+0000] {processor.py:153} INFO - Started process (PID=11711) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:37.932+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:52:37.933+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:52:37.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:37.947+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:52:37.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:52:37.948+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:52:37.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T04:53:08.514+0000] {processor.py:153} INFO - Started process (PID=11823) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:08.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:53:08.516+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:53:08.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:08.534+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:53:08.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:53:08.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:08.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T04:53:39.114+0000] {processor.py:153} INFO - Started process (PID=11911) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:39.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:53:39.115+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:53:39.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:39.129+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:53:39.127+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:53:39.130+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:53:39.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.035 seconds
[2023-03-14T04:54:09.686+0000] {processor.py:153} INFO - Started process (PID=12023) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:09.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:54:09.688+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:54:09.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:09.708+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:54:09.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:54:09.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:09.728+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2023-03-14T04:54:40.368+0000] {processor.py:153} INFO - Started process (PID=12111) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:40.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:54:40.370+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:54:40.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:40.382+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:54:40.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:54:40.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:54:40.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.030 seconds
[2023-03-14T04:55:10.846+0000] {processor.py:153} INFO - Started process (PID=12223) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:10.847+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:55:10.848+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:55:10.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:10.870+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:55:10.866+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:55:10.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:10.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.067 seconds
[2023-03-14T04:55:41.193+0000] {processor.py:153} INFO - Started process (PID=12311) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:41.194+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:55:41.195+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:55:41.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:41.210+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:55:41.207+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:55:41.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:55:41.231+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T04:56:11.349+0000] {processor.py:153} INFO - Started process (PID=12423) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:11.350+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:56:11.351+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:56:11.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:11.368+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:56:11.365+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:56:11.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:11.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:56:42.242+0000] {processor.py:153} INFO - Started process (PID=12511) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:42.243+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:56:42.243+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:56:42.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:42.259+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:56:42.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:56:42.260+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:56:42.287+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-14T04:57:12.788+0000] {processor.py:153} INFO - Started process (PID=12623) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:12.789+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:57:12.789+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:57:12.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:12.802+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:57:12.800+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:57:12.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:12.827+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:57:43.573+0000] {processor.py:153} INFO - Started process (PID=12711) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:43.573+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:57:43.574+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:57:43.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:43.587+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:57:43.585+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:57:43.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:57:43.613+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:58:14.210+0000] {processor.py:153} INFO - Started process (PID=12823) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:14.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:58:14.211+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:58:14.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:14.224+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:58:14.222+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:58:14.225+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:14.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T04:58:44.912+0000] {processor.py:153} INFO - Started process (PID=12911) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:44.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:58:44.913+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:58:44.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:44.927+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:58:44.925+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:58:44.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:58:44.943+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.033 seconds
[2023-03-14T04:59:15.477+0000] {processor.py:153} INFO - Started process (PID=13008) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:15.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:59:15.483+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:15.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:15.539+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:15.529+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:59:15.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:15.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.127 seconds
[2023-03-14T04:59:45.817+0000] {processor.py:153} INFO - Started process (PID=13111) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:45.818+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:59:45.819+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:45.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:45.832+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:45.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:59:45.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:45.849+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.034 seconds
[2023-03-14T04:59:56.374+0000] {processor.py:153} INFO - Started process (PID=13144) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:56.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T04:59:56.376+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:56.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:56.422+0000] {logging_mixin.py:137} INFO - [2023-03-14T04:59:56.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T04:59:56.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T04:59:56.449+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.080 seconds
[2023-03-14T05:00:27.105+0000] {processor.py:153} INFO - Started process (PID=13232) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:27.106+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:00:27.107+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:00:27.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:27.125+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:00:27.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:00:27.126+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:27.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T05:00:57.767+0000] {processor.py:153} INFO - Started process (PID=13344) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:57.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:00:57.768+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:00:57.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:57.790+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:00:57.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:00:57.792+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:00:57.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.060 seconds
[2023-03-14T05:01:28.352+0000] {processor.py:153} INFO - Started process (PID=13432) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:28.352+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:01:28.353+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:01:28.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:28.367+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:01:28.365+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:01:28.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:28.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.035 seconds
[2023-03-14T05:01:58.797+0000] {processor.py:153} INFO - Started process (PID=13544) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:58.798+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:01:58.799+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:01:58.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:58.817+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:01:58.813+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:01:58.818+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:01:58.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.056 seconds
[2023-03-14T05:02:29.658+0000] {processor.py:153} INFO - Started process (PID=13632) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:02:29.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:02:29.659+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:02:29.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:02:29.672+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:02:29.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:02:29.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:02:29.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.034 seconds
[2023-03-14T05:03:00.338+0000] {processor.py:153} INFO - Started process (PID=13744) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:00.339+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:03:00.340+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:03:00.340+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:00.360+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:03:00.356+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:03:00.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:00.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.058 seconds
[2023-03-14T05:03:30.847+0000] {processor.py:153} INFO - Started process (PID=13832) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:30.848+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:03:30.848+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:03:30.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:30.862+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:03:30.860+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:03:30.863+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:03:30.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2023-03-14T05:04:01.552+0000] {processor.py:153} INFO - Started process (PID=13929) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:01.553+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:04:01.554+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:04:01.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:01.570+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:04:01.567+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:04:01.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:01.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.056 seconds
[2023-03-14T05:04:32.244+0000] {processor.py:153} INFO - Started process (PID=14032) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:32.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:04:32.245+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:04:32.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:32.259+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:04:32.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:04:32.260+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:04:32.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2023-03-14T05:05:02.366+0000] {processor.py:153} INFO - Started process (PID=14120) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:02.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:05:02.367+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:05:02.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:02.380+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:05:02.378+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:05:02.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:02.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:05:32.446+0000] {processor.py:153} INFO - Started process (PID=14232) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:32.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:05:32.449+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:05:32.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:32.477+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:05:32.472+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:05:32.480+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:05:32.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.070 seconds
[2023-03-14T05:06:02.785+0000] {processor.py:153} INFO - Started process (PID=14314) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:02.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:06:02.787+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:06:02.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:02.808+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:06:02.805+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:06:02.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:02.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.058 seconds
[2023-03-14T05:06:33.465+0000] {processor.py:153} INFO - Started process (PID=14402) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:33.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:06:33.466+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:06:33.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:33.481+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:06:33.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:06:33.482+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:06:33.501+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.038 seconds
[2023-03-14T05:07:04.204+0000] {processor.py:153} INFO - Started process (PID=14514) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:04.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:07:04.206+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:07:04.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:04.225+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:07:04.222+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:07:04.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:04.258+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.057 seconds
[2023-03-14T05:07:34.293+0000] {processor.py:153} INFO - Started process (PID=14602) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:34.294+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:07:34.295+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:07:34.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:34.317+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:07:34.314+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:07:34.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:07:34.384+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.094 seconds
[2023-03-14T05:08:05.163+0000] {processor.py:153} INFO - Started process (PID=14712) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:05.164+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:08:05.166+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:08:05.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:05.184+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:08:05.181+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:08:05.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:05.206+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.047 seconds
[2023-03-14T05:08:35.804+0000] {processor.py:153} INFO - Started process (PID=14800) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:35.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:08:35.806+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:08:35.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:35.823+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:08:35.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:08:35.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:08:35.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.039 seconds
[2023-03-14T05:09:06.319+0000] {processor.py:153} INFO - Started process (PID=14912) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:06.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:09:06.320+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:09:06.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:06.338+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:09:06.335+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:09:06.340+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:06.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.055 seconds
[2023-03-14T05:09:37.352+0000] {processor.py:153} INFO - Started process (PID=15000) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:37.352+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:09:37.353+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:09:37.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:37.367+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:09:37.365+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:09:37.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:09:37.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.035 seconds
[2023-03-14T05:10:08.176+0000] {processor.py:153} INFO - Started process (PID=15112) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:08.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:10:08.177+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:10:08.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:08.192+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:10:08.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:10:08.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:08.217+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:10:39.019+0000] {processor.py:153} INFO - Started process (PID=15200) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:39.020+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:10:39.021+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:10:39.021+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:39.035+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:10:39.032+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:10:39.036+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:10:39.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.047 seconds
[2023-03-14T05:11:09.790+0000] {processor.py:153} INFO - Started process (PID=15312) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:09.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:11:09.792+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:11:09.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:09.809+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:11:09.806+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:11:09.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:09.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T05:11:40.385+0000] {processor.py:153} INFO - Started process (PID=15400) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:40.386+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:11:40.387+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:11:40.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:40.418+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:11:40.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:11:40.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:11:40.450+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.072 seconds
[2023-03-14T05:12:10.796+0000] {processor.py:153} INFO - Started process (PID=15495) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:10.799+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:12:10.801+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:12:10.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:10.856+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:12:10.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:12:10.859+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:10.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.107 seconds
[2023-03-14T05:12:41.799+0000] {processor.py:153} INFO - Started process (PID=15600) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:41.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:12:41.800+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:12:41.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:41.816+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:12:41.813+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:12:41.817+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:12:41.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.055 seconds
[2023-03-14T05:13:11.888+0000] {processor.py:153} INFO - Started process (PID=15688) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:11.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:13:11.890+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:13:11.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:11.903+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:13:11.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:13:11.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:11.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.034 seconds
[2023-03-14T05:13:42.136+0000] {processor.py:153} INFO - Started process (PID=15800) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:42.137+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:13:42.138+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:13:42.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:42.163+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:13:42.157+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:13:42.164+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:13:42.200+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.068 seconds
[2023-03-14T05:14:12.459+0000] {processor.py:153} INFO - Started process (PID=15888) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:12.460+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:14:12.461+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:14:12.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:12.480+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:14:12.477+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:14:12.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:12.514+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.058 seconds
[2023-03-14T05:14:42.769+0000] {processor.py:153} INFO - Started process (PID=15983) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:42.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:14:42.771+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:14:42.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:42.792+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:14:42.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:14:42.794+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:14:42.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-14T05:15:12.922+0000] {processor.py:153} INFO - Started process (PID=16088) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:12.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:15:12.924+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:15:12.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:12.947+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:15:12.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:15:12.949+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:12.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.054 seconds
[2023-03-14T05:15:43.196+0000] {processor.py:153} INFO - Started process (PID=16176) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:43.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:15:43.198+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:15:43.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:43.219+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:15:43.216+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:15:43.221+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:15:43.244+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.052 seconds
[2023-03-14T05:16:13.603+0000] {processor.py:153} INFO - Started process (PID=16289) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:13.604+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:16:13.605+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:16:13.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:13.628+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:16:13.624+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:16:13.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:13.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.053 seconds
[2023-03-14T05:16:44.272+0000] {processor.py:153} INFO - Started process (PID=16377) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:44.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:16:44.274+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:16:44.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:44.288+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:16:44.285+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:16:44.288+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:16:44.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T05:17:14.940+0000] {processor.py:153} INFO - Started process (PID=16467) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:14.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:17:14.941+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:17:14.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:14.957+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:17:14.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:17:14.958+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:14.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T05:17:45.633+0000] {processor.py:153} INFO - Started process (PID=16577) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:45.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:17:45.636+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:17:45.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:45.655+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:17:45.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:17:45.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:17:45.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-14T05:18:16.042+0000] {processor.py:153} INFO - Started process (PID=16665) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:16.043+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:18:16.044+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:18:16.044+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:16.062+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:18:16.059+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:18:16.064+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:16.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.057 seconds
[2023-03-14T05:18:46.503+0000] {processor.py:153} INFO - Started process (PID=16762) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:46.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:18:46.505+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:18:46.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:46.526+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:18:46.523+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:18:46.527+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:18:46.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.056 seconds
[2023-03-14T05:19:17.422+0000] {processor.py:153} INFO - Started process (PID=16865) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:17.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:19:17.425+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:19:17.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:17.446+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:19:17.443+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:19:17.448+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:17.470+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-14T05:19:47.567+0000] {processor.py:153} INFO - Started process (PID=16953) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:47.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:19:47.569+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:19:47.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:47.582+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:19:47.580+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:19:47.583+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:19:47.608+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T05:20:17.830+0000] {processor.py:153} INFO - Started process (PID=17065) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:17.831+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:20:17.831+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:20:17.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:17.849+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:20:17.847+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:20:17.850+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:17.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-14T05:20:48.370+0000] {processor.py:153} INFO - Started process (PID=17153) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:48.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:20:48.372+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:20:48.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:48.394+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:20:48.391+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:20:48.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:20:48.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.069 seconds
[2023-03-14T05:21:19.167+0000] {processor.py:153} INFO - Started process (PID=17250) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:19.168+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:21:19.169+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:21:19.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:19.191+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:21:19.187+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:21:19.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:19.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.061 seconds
[2023-03-14T05:21:49.332+0000] {processor.py:153} INFO - Started process (PID=17353) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:49.332+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:21:49.333+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:21:49.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:49.346+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:21:49.344+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:21:49.346+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:21:49.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.033 seconds
[2023-03-14T05:22:20.190+0000] {processor.py:153} INFO - Started process (PID=17441) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:20.191+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:22:20.192+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:22:20.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:20.211+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:22:20.208+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:22:20.213+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:20.236+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-14T05:22:50.850+0000] {processor.py:153} INFO - Started process (PID=17553) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:50.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:22:50.851+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:22:50.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:50.866+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:22:50.863+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:22:50.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:22:50.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.037 seconds
[2023-03-14T05:23:21.491+0000] {processor.py:153} INFO - Started process (PID=17641) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:21.493+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:23:21.495+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:23:21.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:21.531+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:23:21.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:23:21.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:21.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.084 seconds
[2023-03-14T05:23:52.498+0000] {processor.py:153} INFO - Started process (PID=17753) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:52.499+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:23:52.500+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:23:52.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:52.518+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:23:52.514+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:23:52.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:23:52.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.057 seconds
[2023-03-14T05:24:23.195+0000] {processor.py:153} INFO - Started process (PID=17841) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:23.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:24:23.197+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:24:23.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:23.217+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:24:23.213+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:24:23.219+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:23.242+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-14T05:24:53.869+0000] {processor.py:153} INFO - Started process (PID=17953) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:53.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:24:53.872+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:24:53.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:53.889+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:24:53.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:24:53.890+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:24:53.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:25:24.134+0000] {processor.py:153} INFO - Started process (PID=18041) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:24.135+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:25:24.136+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:25:24.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:24.161+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:25:24.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:25:24.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:24.189+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.058 seconds
[2023-03-14T05:25:54.933+0000] {processor.py:153} INFO - Started process (PID=18129) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:54.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:25:54.935+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:25:54.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:54.955+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:25:54.952+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:25:54.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:25:54.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
[2023-03-14T05:26:25.629+0000] {processor.py:153} INFO - Started process (PID=18241) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:25.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:26:25.631+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:26:25.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:25.649+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:26:25.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:26:25.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:25.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T05:26:56.375+0000] {processor.py:153} INFO - Started process (PID=18329) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:56.376+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:26:56.377+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:26:56.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:56.399+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:26:56.395+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:26:56.401+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:26:56.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-14T05:27:26.627+0000] {processor.py:153} INFO - Started process (PID=18441) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:26.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:27:26.628+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:27:26.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:26.649+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:27:26.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:27:26.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:26.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:27:56.838+0000] {processor.py:153} INFO - Started process (PID=18529) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:56.839+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:27:56.839+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:27:56.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:56.852+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:27:56.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:27:56.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:27:56.879+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:28:27.027+0000] {processor.py:153} INFO - Started process (PID=18617) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:27.028+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:28:27.029+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:28:27.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:27.044+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:28:27.041+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:28:27.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:27.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.035 seconds
[2023-03-14T05:28:57.671+0000] {processor.py:153} INFO - Started process (PID=18729) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:57.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:28:57.673+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:28:57.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:57.688+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:28:57.686+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:28:57.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:28:57.717+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-14T05:29:28.346+0000] {processor.py:153} INFO - Started process (PID=18817) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:28.347+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:29:28.348+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:29:28.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:28.363+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:29:28.361+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:29:28.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:28.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.037 seconds
[2023-03-14T05:29:59.220+0000] {processor.py:153} INFO - Started process (PID=18929) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:59.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:29:59.221+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:29:59.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:59.240+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:29:59.237+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:29:59.242+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:29:59.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T05:30:30.000+0000] {processor.py:153} INFO - Started process (PID=19017) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:30:30.001+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:30:30.001+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:30:30.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:30:30.019+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:30:30.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:30:30.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:30:30.039+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.041 seconds
[2023-03-14T05:31:00.931+0000] {processor.py:153} INFO - Started process (PID=19114) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:00.932+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:31:00.933+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:31:00.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:00.949+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:31:00.947+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:31:00.951+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:00.978+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2023-03-14T05:31:31.578+0000] {processor.py:153} INFO - Started process (PID=19217) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:31.579+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:31:31.580+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:31:31.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:31.594+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:31:31.592+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:31:31.595+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:31:31.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.038 seconds
[2023-03-14T05:32:02.272+0000] {processor.py:153} INFO - Started process (PID=19306) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:02.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:32:02.274+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:32:02.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:02.290+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:32:02.287+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:32:02.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:02.319+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2023-03-14T05:32:32.625+0000] {processor.py:153} INFO - Started process (PID=19418) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:32.626+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:32:32.627+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:32:32.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:32.644+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:32:32.641+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:32:32.645+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:32:32.663+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T05:33:02.910+0000] {processor.py:153} INFO - Started process (PID=19506) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:02.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:33:02.912+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:33:02.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:02.928+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:33:02.925+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:33:02.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:02.956+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-14T05:33:33.455+0000] {processor.py:153} INFO - Started process (PID=19618) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:33.455+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:33:33.456+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:33:33.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:33.471+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:33:33.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:33:33.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:33:33.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.037 seconds
[2023-03-14T05:34:03.997+0000] {processor.py:153} INFO - Started process (PID=19706) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:03.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:34:03.998+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:34:03.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:04.016+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:34:04.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:34:04.017+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:04.040+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.046 seconds
[2023-03-14T05:34:34.297+0000] {processor.py:153} INFO - Started process (PID=19818) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:34.298+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:34:34.299+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:34:34.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:34.317+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:34:34.314+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:34:34.318+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:34:34.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.053 seconds
[2023-03-14T05:35:05.070+0000] {processor.py:153} INFO - Started process (PID=19906) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:05.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:35:05.072+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:35:05.072+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:05.083+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:35:05.081+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:35:05.084+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:05.109+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-14T05:35:35.694+0000] {processor.py:153} INFO - Started process (PID=20018) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:35.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:35:35.697+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:35:35.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:35.715+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:35:35.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:35:35.716+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:35:35.735+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-14T05:36:05.948+0000] {processor.py:153} INFO - Started process (PID=20106) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:05.949+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:36:05.949+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:36:05.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:05.962+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:36:05.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:36:05.963+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:05.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.033 seconds
[2023-03-14T05:36:36.621+0000] {processor.py:153} INFO - Started process (PID=20200) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:36.622+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:36:36.622+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:36:36.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:36.637+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:36:36.635+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:36:36.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:36:36.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.034 seconds
[2023-03-14T05:37:06.923+0000] {processor.py:153} INFO - Started process (PID=20306) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:06.924+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:37:06.924+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:37:06.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:06.937+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:37:06.935+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:37:06.938+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:06.963+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-14T05:37:37.447+0000] {processor.py:153} INFO - Started process (PID=20394) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:37.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:37:37.449+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:37:37.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:37.465+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:37:37.462+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:37:37.466+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:37:37.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.038 seconds
[2023-03-14T05:38:07.533+0000] {processor.py:153} INFO - Started process (PID=20506) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:07.534+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:38:07.535+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:38:07.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:07.551+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:38:07.548+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:38:07.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:07.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.040 seconds
[2023-03-14T05:38:38.215+0000] {processor.py:153} INFO - Started process (PID=20594) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:38.216+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-14T05:38:38.217+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:38:38.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:38.235+0000] {logging_mixin.py:137} INFO - [2023-03-14T05:38:38.231+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 6, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-14T05:38:38.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-14T05:38:38.258+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.045 seconds
